services:
  python-agent:
    build:
      context: ./python-agent
    container_name: python-agent
    ports:
      - "8000:8000"
    env_file:
      - ./python-agent/.env

  dotnet-api:
    build:
      context: ./dotnet-api
      dockerfile: ./LogSage.Api/Dockerfile
    container_name: dotnet-api
    ports:
      - "5000:80"
    depends_on:
      - python-agent